### PR TITLE
Simple fix to make it work with Leaflet 1.0.1.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by aparshin** [comment]
Thank you for the PR!

Have you tested this fix with Leaflet 1.0.1? `L.GridLayer` requires `createTile()` method implementation, that is missing in your PR.

Another issue is backward compatibility with Leaflet 0.7.x - it will be great to support both versions simultaneously.

**Comment by ghost** [comment]
You're welcome. I have indeed tested it with Leaflet 1.0.1, as one of our internal web applications uses it. Didn't have any issues on Firefox, Chrome, IE 10/11 or Edge. 

I'll see what I can do re backwards compatibility with Leaflet 0.7.x (might be a few days before I can work on it, though).

**Comment by ghost** [comment]
Hi again,

I've modified the patch to support both Leaflet 0.7.x. and Leaflet 1.0.1. The patch has been tested on our development server (briefly with 0.7.x but ongoing with 1.0.1).

**Comment by aparshin** [comment]
Hi Joshua,

I've tested your PR and found problems with temporal layers when `setTransparent` option is set to true. For example, try to add to your map the following layer:

```
new L.GIBSLayer(
        'MODIS_Aqua_CorrectedReflectance_TrueColor',
        {date: new Date('10/17/2016'), transparent: true}
);
```

It works with Leaflet 0.7, but not with 1.0!

Could you, please, check this test case.

**Comment by ghost** [comment]
Hmm. Seems none of the MODIS layers want to show up on my system now. It's not throwing any exceptions, either, so I'm going to have to do some digging. I'll try to sort it out as soon as I can (time permitting), but it may be a few weeks if I can't solve it in the next day or two.

Update: the issue isn't setting `transparent` to true, but including it as an option. It changes the way it's drawn and the issue is somewhere there. I'll keep looking.

**Comment by aparshin** [comment]
Thank you for your help!

**Comment by ghost** [comment]
I've updated it to try to resolve the problem with the transparent layers. I've tested the MODIS layers with transparency on IE (9 & 10 throw a security error, which is a known bug in IE; 11 works fine), Edge, Firefox and Chrome.

**Comment by aparshin** [comment]
Hi Joshua,

Sorry for delay with PR review!

Now it works fine! The only problem I've noticed is code duplication: could you, please, extract common code of `drawTile()` and `createTile()` methods in a separate function and call it from both `drawTile()` and `createTile()`.

After that I'll merge the PR.

Once again thank you for your help!

**Comment by ghost** [comment]
I've extracted what I can from `drawTile` and `createTile`, although it's probably not worth it to try combining all the code (diminishing returns, etc.).

Checked it briefly (IE11, Firefox, Chrome) and it still works. Let me know if there's any further issues.

**Comment by aparshin** [comment]
Finally merged! Great work.

Thank you for the contribution!

**Comment by ghost** [comment]
You're welcome and thanks for your patience. Sorry about the indentation problem - didn't realise my editor was doing it differently until I saw the comparison on GitHub (looked fine in Notepad++).

**Comment by aparshin** [comment]
I often have the same problem with Notepad++, don't worry about that! :)

**Pull request merged**
